localisation:
  ros__parameters:
    wheel_radius: 0.05
    wheel_base: 0.19
    update_rate: 50.0
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    world_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint"
    kr: 0.002
    kl: 0.002
    use_ekf: true
    ekf_r_dist: 0.05
    ekf_r_bearing: 0.05
    use_ground_truth_pose: false
    marker_ids: [705, 706, 70, 703, 708, 75, 702]
    marker_pos_x: [-0.500, -0.500, -1.300, 0.400, -0.350, 0.800, 0.300]
    marker_pos_y: [-0.880, 0.820, 0.200, -0.280, -0.250, 1.120, -1.150]
