localisation:
  ros__parameters:
    x0: 1.20
    y0: -1.00
    theta0: 1.57
    initial_x: 1.20
    initial_y: -1.00
    initial_theta: 1.57
    publish_map_odom_tf: true
    update_rate: 50.0
    wheel_radius: 0.05
    wheel_base: 0.19
    world_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint"
    kr: 0.002
    kl: 0.002
    use_ekf: true
    ekf_r_dist: 0.05
    ekf_r_bearing: 0.05
    marker_size_m: 0.18
    aruco_dictionary: "DICT_4X4_1000"
    marker_ids:   [70,     706,    75,     701,    703,    705,    708,    702]
    marker_pos_x: [-1.634, -0.972,  0.792,  1.634,  0.945, -0.109, -0.324,  0.303]
    marker_pos_y: [ 0.224,  0.854,  1.621,  0.230, -0.354, -0.971, -0.370, -1.277]
