localisation:
  ros__parameters:
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    wheel_radius: 0.05
    wheel_base: 0.19
    odom_frame: "odom"
    base_frame: "base_footprint"
    kr: 0.002
    kl: 0.002
    use_ekf: true
    ekf_r_dist: 0.05
    ekf_r_bearing: 0.05
    marker_ids:   [0,     1,    2,     3   ]
    marker_pos_x: [-1.3,  1.0,  1.0,  -1.3 ]
    marker_pos_y: [ 0.9,  0.9, -0.9,  -0.9 ]
