# Config de navegacion (Bug2 + wall-following) para FISICO.
# Aplica al nodo: bug_controller

bug_controller:
  ros__parameters:
    controller_update_rate: 25.0
    controller_type: "BUG2"

    # Seleccion de waypoint por topico:
    # ros2 topic pub --once /selected_waypoint std_msgs/msg/Int32 "{data: 2}"
    waypoint_topic: "selected_waypoint"

    # Tolerancia de llegada al waypoint
    distance_tolerance: 0.16
    goal_capture_tolerance: 0.16
    blocked_goal_tolerance: 0.23
    
    # Velocidades
    v_max: 0.12
    w_max: 1.2
    p2p_v_Kp: 0.8
    p2p_w_Kp: 0.9

    # Seguimiento de pared
    following_walls_distance: 0.25
    front_stop_distance: 0.24
    lookahead_distance: 0.30
    bug2_line_tol: 0.20 #podríamos subir este a 0.25
    min_wall_follow_distance: 0.08 #bajar a 0.05
    fw_w_Kp: 1.0
    fw_e_Kp: 3.5
    fw_linear_speed: 0.12
    fw_outer_corner_angular_speed: 1.2
    fw_outer_corner_linear_speed: 0.16

    # Aperturas angulares LiDAR (rad)
    side_open_angle: 0.5236
    front_open_angle: 0.4

    # Offset LiDAR
    lidar_yaw_offset: 3.14159

    # Suavizado angular
    max_w_accel: 4.0

    # Waypoints del laberinto (índice 1..6)
    # WP1: inicio      WP2: pasillo izq   WP3: esquina inf-izq
    # WP4: centro-der  WP5: esquina inf-der  WP6: centro
    waypoints_x: [0.36,   0.36,  0.36,  2.18,  2.72,  1.70]
    waypoints_y: [-0.275, -0.94, -2.72, -0.30, -2.72, -2.04]
    loop: false